### ISSUE TITLE
error code ERR_STREAM_WRITE_AFTER_END

### ISSUE THREAD

**Issue by cromatikap** [mitsosf/solidity-lottery#1]
I dude, I have a problem to run your program x)

I did that :
`$ git clone https://github.com/mitsosf/solidity-lottery.git`
`$ cd solidity-lottery/lottery-react`
`$ npm install`

output:
```
npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/axel/.npm/_logs/2018-04-02T09_14_20_558Z-debug.log
```

`$ cat  /home/axel/.npm/_logs/2018-04-02T09_14_20_558Z-debug.log`
```
15404 silly tarball trying source-map@0.5.7 by hash: sha1-igOdLRAh0i0eoUyA2OpGi6LvP8w=
15405 silly extract balanced-match@0.4.2 extracted to /home/axel/Desktop/solidity-lottery/lottery-react/node_modules/.staging/balanced-match-1b4de660 (150ms)
15406 silly extract find-up@1.1.2 extracted to /home/axel/Desktop/solidity-lottery/lottery-react/node_modules/.staging/find-up-939d7941 (144ms)
15407 verbose stack Error [ERR_STREAM_WRITE_AFTER_END]: write after end
15407 verbose stack     at writeAfterEnd (_stream_writable.js:241:12)
15407 verbose stack     at PassThrough.Writable.write (_stream_writable.js:291:5)
15407 verbose stack     at PassThrough.Writable.end (_stream_writable.js:576:10)
15407 verbose stack     at ReadEntry.entry.on (/usr/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
15407 verbose stack     at ReadEntry.emit (events.js:185:15)
15407 verbose stack     at ReadEntry.emit (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
15407 verbose stack     at ReadEntry.[maybeEmitEnd] (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
15407 verbose stack     at ReadEntry.end (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
15407 verbose stack     at Unpack.[consumeBody] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
15407 verbose stack     at Unpack.[consumeChunkSub] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
15407 verbose stack     at Unpack.[consumeChunk] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
15407 verbose stack     at Unzip.(anonymous function).on.chunk (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
15407 verbose stack     at Unzip.emit (events.js:180:13)
15407 verbose stack     at Unzip.emit (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
15407 verbose stack     at Unzip.write (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:90:17)
15407 verbose stack     at Unzip.write (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
15408 verbose cwd /home/axel/Desktop/solidity-lottery/lottery-react
15409 verbose Linux 4.15.13-1-ARCH
15410 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
15411 verbose node v9.10.1
15412 verbose npm  v5.8.0
15413 error code ERR_STREAM_WRITE_AFTER_END
15414 error write after end
15415 verbose exit [ 1, true ]
```

npm start obviously fail :p

**Comment by mitsosf** [comment]
Hey,

I tried it on my machine and it worked. I did a little research and I think the issue is the specific node and npm versions you're running on your end, people have been encountering similar errors while using node v.9.x.x combined with specific versions of npm. I am personally using `node v.8.6.0` and `npm v.5.3.0`. Try downgrading to these and that should do the trick. Let me know if it was resolved :)

**Comment by cromatikap** [comment]
I runned a system upgrade and the `$ npm install` worked after it (I didn't check if node were among the updated packages), I have node v9.10.1 and npm v5.8.0

Now `$ npm start` works well but I have this error in the browser : 
```
TypeError: window.web3 is undefined
./src/web3.js
src/web3.js:4
```

`$ cat src/web3.js`
```
import Web3 from 'web3';

//We want to use our version of Web3 instead of Metamask's
const web3 = new Web3(window.web3.currentProvider);

export default web3;
```

**Comment by cromatikap** [comment]
I forgot to install metamask, my fault :D
